drop table if exists bookmarks;

create table bookmarks (
  id INTEGER primary key generated by default as identity,
  name TEXT,
  tag TEXT,
  url TEXT
);

insert into bookmarks (name, tag, url)
values
  ('ESPN', 'Sports', 'ESPN.com'),
  ('CNN', 'News', 'Cnn.com'),
  ('Reddit', 'Random', 'Reddit.com'),
  ('Netflix', 'Streaming', 'Netflix.com'),
  ('Hulu', 'Streaming', 'Hulu.com'),
  ('Facebook', 'Social Media', 'Facebook.com'),
  ('Instagram', 'Social Media', 'Instagram.com'),
  ('Twitter', 'Social Media', 'Twitter.com'),
  ('IGN', 'Gaming', 'IGN.com'),
  ('Amazon', 'Shopping', 'Amazon.com');